[package]
name = "fds"
version = "1.0.0"
authors = []

[addresses]
fds="0x4d251d5213497ef24972efcc03771892a7a72fcda61bf98af7ab67cd8a267d46"
[dev-addresses]

[dependencies.AptosFramework]
git = "https://github.com/aptos-labs/aptos-core.git"
rev = "rewards"
subdir = "aptos-move/framework/aptos-framework"

[dependencies.AptosTokenObjects]
git = "https://github.com/aptos-labs/aptos-core.git"
subdir = "aptos-move/framework/aptos-token-objects/"
rev = "rewards"

[dev-dependencies]
